### ISSUE TITLE
[NaN].includes(NaN) === true?

### ISSUE THREAD

**Issue by jacobp100** [tc39/Array.prototype.includes#29]
Surely this is going to just confuse people. How about to do this check,
```js
assert([NaN].some(Number.isNaN) === true)
```
which already works.

**Comment by ljharb** [comment]
Why would it confuse people that an array with `NaN` in it, includes `NaN`?

**Comment by jacobp100** [comment]
Because the indexOf is -1. It's just giving ECMAScript more special, weird cases, which just increases the rote learning for the language.

**Comment by rwaldron** [comment]
@jacobp100 

- When `indexOf` doesn't find `NaN`, that's a bug. `includes` fixes that bug. 
  
  > SameValueZero is generally the better choice, as it allows you to detect if an array includes a NaN. The argument for Strict Equality Comparison boils down to "bug compatibility" with Array.prototype.indexOf. But one of the purposes of Array.prototype.includes is to steer users away from creating these sort of bugs.
- If you need an `indexOf`-like operation to find the index of the first `NaN`: `[NaN].findIndex(Number.isNaN)`

**Comment by domenic** [comment]
@arv and I also have vague plans to test if fixing `indexOf` breaks the web or not. It's possible it doesn't in which case we could maybe fix it in the spec and other browsers.

**Comment by rwaldron** [comment]
Oh, that would be great!

**Comment by jacobp100** [comment]
@rwaldron I think it's subjective whether it's a bug or not. But since you mention the `findIndex` thing, I'm going to raise that `some(Number.isNaN)` will do includes NaN. I think either both find NaN, or neither, otherwise you force developers to recognise a difference between the two functions (rote learning)

**Comment by ljharb** [comment]
@jacobp100 `[1,NaN].some(Number.isNaN)` already returns true - any iteration method that takes a function is taking user-defined behavior, so there's no consistency requirement there at all. It's only `indexOf`/`lastIndexOf` and `includes` that take a search value, and `includes` is meant to fix the confusing behavior from `indexOf`/`lastIndexOf`.

**Comment by jacobp100** [comment]
My point was that it is already trivial to find NaN in an array, so includes NaN will add little value there.
I get that it is confusing at first that NaN won't show up in `indexOf`. It also doesn't show up in `switch` statements, `if` statements, and basically anywhere else. Currently, once you learn how it works, you know it works the same everywhere. This would then be the only case where it recognises NaN without using `isNaN`, which then makes it more confusing.
FWIW, Python doesn't recognise NaN in an array.
```python
float('NaN') in [float('NaN')]
False
```

**Comment by leobalter** [comment]
> I also have vague plans to test if fixing indexOf breaks the web or not. It's possible it doesn't in which case we could maybe fix it in the spec and other browsers.

@domenic did you test it? indexOf now seems so weird and broken with findIndex and includes. 

I'm sorry to ress this thread, I didn't find any other info from the meeting notes or this repo.

**Comment by domenic** [comment]
No, I'm sorry, I didn't.
