### ISSUE TITLE
Holes?

### ISSUE THREAD

**Issue by ljharb** [tc39/Array.prototype.includes#31]
What happens with a sparse array? Should `Array(1).includes()` be `true` (indicating that holes are traversed) or `false` (indicating that holes are skipped)?

All of the Array.prototype methods in ES6/ES2015 skip holes, so I'd expect `includes` to do so as well for consistency.

**Comment by domenic** [comment]
Dupe of #15.

**Comment by ljharb** [comment]
A ha, thank you for confirming
