### ISSUE TITLE
Add "includes" to unscopables?

### ISSUE THREAD

**Issue by anba** [tc39/Array.prototype.includes#34]
I didn't find any info why it's okay to omit "includes" from unscopables. ES2015 added all new Array.prototype methods to `Array.prototype[@@unscopables]` even though only `Array.prototype.values` was problematic for web-compatibility.

**Comment by domenic** [comment]
It never came up, and hasn't proven necessary, so I don't really feel inclined to make engines revisit the issue. We can bring it up at TC39 though to see if anyone wants to do so.
