### ISSUE TITLE
add "excludes" for symmetry

### ISSUE THREAD

**Issue by mahonnaise** [tc39/Array.prototype.includes#35]
If it would be still called "contains" this would have never crossed my mind, but "includes"/"excludes" feels very natural.

``` JavaScript
array.excludes(thing)
```

instead of:

``` JavaScript
!array.includes(thing)
```

Having some '!' somewhere at the very left always feels kinda clunky - even more so if there are a few other method calls before you get to this final `includes` call.

Interestingly, the ES3/5/6 flavor with `indexOf` doesn't have this kind of issue because the "=== -1" or "!== -1" bit comes at the very end.

Includes:

``` JavaScript
array.indexOf(thing) !== -1
```

Excludes:

``` JavaScript
 array.indexOf(thing) === -1
```

**Comment by domenic** [comment]
I have no intention of championing such an additional method. I like compositional language features, like includes + negation, instead of a kitchen sink containing every negation for every method in the language.
