### ISSUE TITLE
why is includes not implemented like the other related methods (find, findIndex etc.)

### ISSUE THREAD

**Issue by marcelh-gh** [tc39/Array.prototype.includes#37]
the way this is implemented right now just works for arrays containing primitives. when you have objects and you want the includes method to target just one of the properties (or maybe some of them), you have to fall back to .findIndex()!==-1 (or other solutions) again.

**example:**
_(code is TypeScript)_

```typescript
interface Data{
  propA: string;
  propB: number;
}
let myDataArray: Data[] = [];

myDataArray.push({ propA: "one", propB: 1 });
myDataArray.push({ propA: "two", propB: 2 });

let result = myDataArray.findIndex(element:Data=>(element.propA==="one"))!==-1;`
```

it would be much nicer and more flexible to be able to just write:

`let result = myDataArray.includes(element: Data => (element.propA === "one"));`

the only "downsides" I can see would be 

1. the selection of the appropriate way of comparison would be left to the user (now its pre-defined in a particular way for strings, numbers etc.)
2. the usage for the most simple case (array of primitives) would be slightly more verbose 
`let result = simpleArray.includes(element => (element === "one"));`
instead of
`let result = simpleArray.includes("one");`

in my opinion the benefits outweigh these two though. also the same rationale applies to `Array.prototype.find` or `Array.prototype.findIndex`.

**Comment by Ltrlg** [comment]
You can use Array#some(predicate) for this.

**Comment by marcelh-gh** [comment]
I am aware of that. Thx. :)
But with the movitivation of `Array.protoype.includes` mostly being about legible code, where 

> you say what you mean,

I still think it should be implemented as explained.
In terms of the details of the comparison regarding NaN etc.: for me  **that** actually is the special case that maybe should get its own method but includes should be in line with all the other "newer" `Array.prototype` methods like find, findIndex, map, reduce etc....  who can be used for any case and offer flexibility
 
Well, with this currently being in stage 4, nothing is gonna happen anytime soon.
But maybe it can be discussed furthermore for the next version of the standard.

**Comment by domenic** [comment]
Just use `some`.
