### ISSUE TITLE
Element.classList.contains but Array.prototype.includes?

### ISSUE THREAD

**Issue by sularome** [tc39/Array.prototype.includes#38]
Don't you think this will be confusing that Element.classList.contains, but Array.prototype.includes?
From the link that you provided you don't want to name this method **contains** because of bug MooTools had 3 years ago? If i create a new library "NewLib.js" that has bug with **Array.prototype.includes** would you change the name again? It doesn't sound reasonable to me.

**Comment by ljharb** [comment]
This proposal has landed in the language; both `String.prototype.includes` and `Array.prototype.includes` exist; in practice this hasn't been a problem.
