### ISSUE TITLE
Why is includes for empty string is always true. 

### ISSUE THREAD

**Issue by Punith-Mithra** [tc39/Array.prototype.includes#39]
I tried `'abc'.includes('') ` it returns true. Is this correct ? I was expecting it to return false.

**Comment by mathiasbynens** [comment]
Why would you expect it to return `false`? Every string includes the empty string an infinite number of times.

**Comment by mathiasbynens** [comment]
Note that this is the repository for `Array.prototype.includes`, not `String.prototype.includes`. And since both are in the upstream spec now, issues should be filed there: https://github.com/tc39/ecma262/issues
