### ISSUE TITLE
Get into JavaScriptCore

### ISSUE THREAD

**Issue by domenic** [tc39/Array.prototype.includes#9]
- [x] Write and submit patch
- [x] Get accepted as experimental (behind a flag)
- [x] Get shipping

**Comment by domenic** [comment]
This is shipping in WebKit per http://www.webkit.org/status.html. If anyone with the latest Safari could confirm the presence or absense of the feature by default, that'd be helpful.

**Comment by hemanth** [comment]
:+1:

**Comment by mathiasbynens** [comment]
The latest stable Safari release (v8.0.7 / 10600.7.12) doesn’t have it yet.

But WebKit Nightly does. (Even v8.0.7 / 10600.7.12 r183911, which is an old version, has it.)
